Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -42,26 +42,41 @@ jobs:
             
             curl -u ${{ secrets.SONAR_TOKEN }} -OL "$Value" >> ./github.json
             cat $PWD/github.json
-            while read jsonDate ;
-            do 
-             metric=$(jq -r '.metric' <<< $jsonData)
-             value=$(jq -r '.value' <<< $jsonData)
-             echo "$metric"
-             
-               if [ "${value%.*}" -lt ${{env.Coverage_value}} ]
-                then
-                 echo "Expected $(metric%.*) - {{env.Coverage_value}}" 
-                 echo "Actual $(metric%.*) - ${value%.*} "
-                 echo "Coverage is fail"
-                 exit 1
-                else
-                echo "Expected $(metric%.*) - {{env.Coverage_value}}" 
-                echo "Actual $(metric%.*) - ${value%.*} "
-                echo "Coverage is fail"
-               fi
-             
-               done <<< $(jq -c '.component.measures[]' $PWD/github.json)
-               cat $PWD/github.json 
+            while read jsonData ;
+            do
+            metric=$(jq -r '.metric' <<< $jsonData)
+            value=$(jq -r '.value'<<< $jsonData)
+            echo "$metric"
+            echo "$value"
+            #echo "${metric%.*}"
+
+            if [ "$metric" == "coverage" ] ;
+              then
+                if [ "${value%.*}" -lt ${{env.COVERAGE-THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.COVERAGE_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.COVERAGE_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
+
+            elif [ "$metric" == "code_smells" ] ;
+              then
+                if [ "${value%.*}" -gt ${{env.CODE_SMELLS_THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
              
                 
                 
