Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -38,25 +38,25 @@ jobs:
          CODE_SMELLS_value: 50
           
        run: | 
-             curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage >> ./github.json
-             cat $PWD/github.json 
+            Value = $(curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage)) 
+            
              
     - name: Compare SonarCloud result with threshold
       env: 
           coverage_threshold: 80
       run: |
                  
-                  value=$(echo "${{job.step[1].outputs.metrics}}"|jq -r '.coverage')
+                
                   
-                     if [["$value" -lt coverage_threshold]]; then
+                     if [["$Value" -lt coverage_threshold]]; then
                       echo "Coverage= passed" >>github.json
                       exit 1
-                    elif [[ "$value" -lt coverage_threshold ]]; then
+                     elif [[ "$Value -lt coverage_threshold ]]; then
                      echo "Coverage= failed" >>github.json
-                   else
-                    echo "Unable to determine Coverage status."
-                    exit 1
-                  fi     
+                     else
+                      echo "Unable to determine Coverage status."
+                      exit 1
+                     fi     
               
      
           
