Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -35,31 +35,81 @@ jobs:
     -  name: API with curl
        shell: bash
        env: 
-         Coverage_value: 10
-         CODE_SMELLS_value: 50
-         Value1: "https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage" 
+         COVERAGE_THRESHOLD: 20
+         CODE_SMELLS_THRESHOLD: 200
+         VULNERABILITIES_THRESHOLD: 6
+        
        run: | 
-            curl --location --request GET 'https://sonarcloud.io/api/measures/component?metricKeys=code_smells,coverage&component=devopsnishu_github-example-package' --header 'Authorization: Bearer ${{ secrets.SONAR_TOKEN }}' > ./github.json 
-           
-            cat $PWD/github.json
-            while read jsonDate ;
-            do 
-             metric=$(jq -r '.metric' <<< $jsonData)
-             value=$(jq -r '.value' <<< $jsonData)
-             echo "$metric"
-             echo "$value"
-             
-               if [ "${value%.*}" -lt ${{env.Coverage_value}} ]
-                then
-                                
-                 echo "Coverage is fail"
-                 exit 1
-                else
-                echo "Coverage is fail"
-               fi  
-                
-             done <<< $(jq -c '.component.measures[]' $PWD/github.json)
-             cat $PWD/github.json       
+            
+            curl --location --request GET 'https://sonarcloud.io/api/measures/component?metricKeys=code_smells,coverage,duplicated_lines_density,vulnerabilities,security_hotspots,critical_violations,bugs&component=ramandevopsnew_java-maven-app' --header 'Authorization: Bearer 4512dc92c65af491dad8c07aa97a7d265f91fb4f' > ./Response.json
+            while read jsonData ;
+            do
+            metric=$(jq -r '.metric' <<< $jsonData)
+            value=$(jq -r '.value'<<< $jsonData)
+            echo "$metric"
+            echo "$value"
+            #echo "${metric%.*}"
+
+            if [ "$metric" == "coverage" ] ;
+              then
+                if [ "${value%.*}" -lt ${{env.COVERAGE-THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.COVERAGE_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.COVERAGE_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
+
+            elif [ "$metric" == "code_smells" ] ;
+              then
+                if [ "${value%.*}" -gt ${{env.CODE_SMELLS_THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.CODE_SMELLS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
+
+            elif [ "$metric" == "vulnerabilities" ] ;
+              then
+                if [ "${value%.*}" -gt ${{env.VULNERABILITIES_THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.VULNERABILITIES_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.VULNERABILITIES_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
+
+            elif [ "$metric" == "critical_violations" ] ;
+              then
+                if [ "${value%.*}" -gt ${{env.CRITICAL_VIOLATIONS_THRESHOLD }} ] ;
+                  then
+                    echo "Expected ${metric%.*} - ${{env.CRITICAL_VIOLATIONS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Failed"
+                    exit 1
+                  else
+                    echo "Expected ${metric%.*} - ${{env.CRITICAL_VIOLATIONS_THRESHOLD}}"
+                    echo "Actual ${metric%.*} - ${value%.*}"
+                    echo "Sonar code coverage Gate: Passed"
+                  fi
+            fi
+            done <<< $(jq -c '.component.measures[]' $PWD/Response.json)
+            cat $PWD/Response.json
+          
+        
  
             
              
