Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -37,19 +37,19 @@ jobs:
          Coverage_value: 10
          CODE_SMELLS_value: 50
           
-       run: |  
-             curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage >> ./github.json
+       run: | 
+             threshold=80
+             curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage,alert_status >> ./github.json
              cat $PWD/github.json
-              if ["$metric"== "coverage"],
-              then
-                if[$(value) -lt "Coverage_value"],
-                 then 
-                  echo "sonar-coverage check :fail"
-                else
-                 echo "sonar-coverage check :pass"
-               else
-                echo "coverage"
-               fi   
+              if [[ "${quality_gate_status}" == "ERROR" ]]; then
+                echo "Quality gate failed. SonarCloud analysis did not meet the threshold."
+              exit 1
+             elif [[ "${quality_gate_status}" == "OK" ]]; then
+             echo "Quality gate passed. SonarCloud analysis meets the threshold."
+             else
+               echo "Unable to determine the quality gate status."
+               exit 1
+             fi 
               
      
           
