Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -40,6 +40,22 @@ jobs:
        run: | 
              curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage >> ./github.json
              cat $PWD/github.json 
+             
+    - name: Compare SonarCloud result with threshold
+      env: 
+          coverage_threshold: 80
+      run: |
+                  curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage
+
+                     if [[$(value) -lt coverage_threshold]]; then
+                      echo "Coverage= passed" >>github.json
+                      exit 1
+                    elif [[ $(value) -lt coverage_threshold ]]; then
+                     echo "Coverage= failed" >>github.json
+                   else
+                    echo "Unable to determine Coverage status."
+                    exit 1
+                  fi     
               
      
           
