Update Sonarscan.yml

diff --git a/.github/workflows/Sonarscan.yml b/.github/workflows/Sonarscan.yml
--- a/.github/workflows/Sonarscan.yml
+++ b/.github/workflows/Sonarscan.yml
@@ -16,18 +16,17 @@ jobs:
         run: sonar-scanner
 
       - name: Compare SonarCloud result with threshold
-         
         env: 
-          coverage_threshold:80
+          coverage_threshold: 80
         run: |
                   curl -u ${{ secrets.SONAR_TOKEN }} -OL https://sonarcloud.io/api/project_badges/measure?project=devopsnishu_github-example-package&metric=coverage
 
-                     if [$(value) -lt coverage_threshold]; then
-                      echo "Coverage= passed >>github.json
+                     if [[$(value) -lt coverage_threshold]]; then
+                      echo "Coverage= passed" >>github.json
                       exit 1
-                  elif [[ "${quality_gate_status}" == "OK" ]]; then
-            echo "Quality gate passed. SonarCloud analysis meets the threshold."
-          else
-            echo "Unable to determine the quality gate status."
-            exit 1
-          fi
+                    elif [[ $(value) -lt coverage_threshold ]]; then
+                     echo "Coverage= failed" >>github.json
+                   else
+                    echo "Unable to determine Coverage status."
+                    exit 1
+                  fi
